forge "http://forge.puppetlabs.com"

mod 'example42/puppi'
mod 'stahnma/epel'
mod 'puppetlabs/firewall'

mod 'puppetlabs/java'
mod 'puppetlabs/tomcat'
mod 'puppetlabs/postgresql'

mod 'maestrodev/rvm'
# mod 'jdowning/rbenv'

mod 'puppetlabs/apache'
mod 'puppetlabs/passenger'

mod 'LafayetteCollegeLibraries/fedora_commons_solr',
     :git => "https://github.com/LafayetteCollegeLibraries/puppet-fedora_commons_solr.git",
     :ref => 'c5d5e2b9d93ad67853b271f982343def4a6567cb'

mod "LafayetteCollegeLibraries/fedora_commons",
    :git => "git@github.com:LafayetteCollegeLibraries/puppet-fedora_commons.git",
    :ref => 'fcac17124f67b3b7b9314e024647d8b8f311d1b5'

mod 'LafayetteCollegeLibraries/fedoragsearch',
    :git => "https://github.com/LafayetteCollegeLibraries/puppet-fedoragsearch.git",
    :ref => '2b0a90bdd078c42abb5eef995ffe169165f7bd70'

#    :git => "https://github.com/LafayetteCollegeLibraries/puppet-sufia_tomcat.git",
#    :ref => '5c574da449d900907bf65e2561e689b1f10d2159'
mod "LafayetteCollegeLibraries/sufia_tomcat", :path => '../../puppet-sufia_tomcat'

